name: Update Neovim Submodule
on:
  repository_dispatch:
    types: [neovim-updated]
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-submodule:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Git config
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Check and update submodule
        run: |
          # Initialize and update the submodule
          git submodule init
          git submodule update

          # Go to submodule directory and fetch latest changes
          cd dot-neovim
          git fetch origin
          SUBMODULE_DEFAULT_BRANCH=$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')
          CURRENT_SHA=$(git rev-parse HEAD)
          LATEST_SHA=$(git rev-parse origin/$SUBMODULE_DEFAULT_BRANCH)

          echo "Current submodule SHA: $CURRENT_SHA"
          echo "Latest submodule SHA: $LATEST_SHA"

          # Fetch and display the Git log
          echo "Fetching git log for the submodule..."
          GIT_LOG=$(git log --oneline -n 10)

          if [ "$CURRENT_SHA" != "$LATEST_SHA" ]; then
            cd ..
            git submodule update --remote dot-neovim
            git add dot-neovim
            SUBMODULE_SHORT_SHA=$(cd dot-neovim && git rev-parse --short HEAD)

            # Capture the latest commit message from the submodule
            LATEST_COMMIT_MESSAGE=$(cd dot-neovim && git log -1 --pretty=%B)

            # Commit with the new message
            # Commit with the new message
            git commit -m "chore(neovim): update submodule to ${SUBMODULE_SHORT_SHA}

            Triggered by commit:
            ${LATEST_COMMIT_MESSAGE}"
            git push
          else
            echo "Submodule is already up to date"
          fi

